name: runrank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.2
  package_info_plus: ^8.0.0
  supabase_flutter: ^2.8.4
  image_picker: ^1.1.2
  file_picker: ^8.0.7
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  pdf: ^3.11.0
  printing: ^5.13.0
  flutter_email_sender: ^6.0.3
  share_plus: ^10.1.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path: ^1.9.1
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  firebase_crashlytics: ^4.3.0
  flutter_stripe: ^12.0.0
  http: ^1.2.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/screenrank_logo.png"
  ios: true
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/screenrank_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/runners_group.JPG
    - assets/images/club_history_runner.jpg
    - assets/images/nnbr_logo.png
    - assets/images/rank_logo.png
    - assets/images/nnbr_cover.png
    - assets/images/eaccl.jpg
    - assets/images/firstclaim.png
    - assets/images/secondclaim.png
    - assets/images/socialclaim.png
    - assets/images/fulleduc.png
    - assets/images/holt10.png
    - assets/images/worstead5m.png
    - assets/images/chasetrain.jpg
    - assets/images/nnbrdocs.png
    - assets/images/pic1.png
    - assets/images/pic2.png
    - assets/images/pic3.png
    - assets/images/pic4.png
    - assets/images/pic5.png
    - assets/images/pic6.png
    - assets/images/pic7.png
    - assets/images/pic8.png
    - assets/images/pic9.png
    - assets/images/pic10.png
    - assets/images/pic11.png
    - assets/images/malcolmball.png
    - assets/images/app_icon_round.png
    - assets/images/screenrank_logo.png
    - assets/images/awards.png
    - assets/images/handicappic.png
    - assets/images/RNR26.png
    - assets/images/rnr.png
